apiVersion: v1
kind: Pod
metadata:
  name: ram-stress
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: "1000Mi"
      limits:
        memory: "2000Mi"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "1500M", "--vm-hang", "1"]